server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  application:
    name: psychology-eureka-registry

logging:
  level:
    root: info

eureka:
  instance:
    hostname: psychology-eureka-centre
    appname: 心理学院-服务注册中心
  client:
    #在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，禁用它的客户端注册行为
    register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false
    #设置与Eureka Server交互的地址，查询服务和注册服务
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000