server:
  port: 8080
  servlet:
    context-path: /centre

# 服务提供者
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 47.110.247.139
    instance-id: 47.110.247.139:${server.port}
  client:
    service-url:
      defaultZone: http://47.110.247.139:8000/eureka

snow-flake:
  machine-id: 1
  room-id: 2

spring:
  application:
    name: psychology-user-centre

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://47.110.247.139:3306/psychology_user_centre?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
      pool-name: user_centre_db_pool

  redis:
    client-name: ${spring.application.name}
    host: 47.110.247.139
    port: 6379
    timeout: 10000ms
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  cache:
    type: redis


mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info

