server:
  port: 8000

spring:
  application:
    name: psychology-registry
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

logging:
  level:
    root: info
eureka:
  instance:
    hostname: 127.0.0.1
    appname: ${spring.application.name}

  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
